/* Original practice variants. Numeric answers use the units shown on each part. */
const TOPICS = [
 ['accounts','国民核算','Contabilità nazionale'],['goods','商品市场','Mercato dei beni'],
 ['finance','金融市场','Mercati finanziari'],['islm','IS–LM','IS–LM'],
 ['labor','劳动与通胀','Lavoro · Phillips · IS–LM–PC'],['growth','长期增长','Crescita · Solow'],
 ['expectations','预期','Aspettative'],['open','开放经济','Economia aperta'],
 ['fiscal','财政与债务','Politica fiscale'],['policy','政策延伸','Estensioni del syllabus']
];
const BANK = [];
const N=(text,answer,solution,unit='',tol=0.02)=>({text,answer,solution,unit,tol});
const T=(text,solution)=>({text,solution});
function O(id,topic,title,context,parts,graph=null){BANK.push({id,type:'open',scope:id.startsWith('P')?'primo':'secondo',topic,title,context,parts,graph});}
function M(id,scope,topic,title,context,options,explanation){
 const rotate=Number(id.slice(1))%4;
 const shuffled=options.slice(rotate).concat(options.slice(0,rotate));
 BANK.push({id,type:'mcq',scope,topic,title,context,options:shuffled,correct:(4-rotate)%4,explanation,extension:['Q30','Q38','Q39'].includes(id)});
}
O('P01','accounts','GDP 的三种计算方法','In un’economia chiusa: un’acciaieria vende input per 400 a un produttore di auto e paga salari per 280; un’impresa alimentare vende beni finali per 300 e paga salari per 220; il produttore di auto vende auto per 1.100, paga salari per 500 e acquista gli input per 400. Non vi sono altre voci.',[
 N('Calcolate il profitto dell’acciaieria.',120,'利润 = 400 − 280 = 120。'),N('Calcolate il profitto del produttore di auto.',200,'利润 = 1,100 − 500 − 400 = 200。'),N('Calcolate il PIL con il metodo dei beni finali.',1400,'最终产品法：300 + 1,100 = 1,400。钢材已包含在汽车价值内。'),T('Verificate il PIL con valore aggiunto e redditi.','增加值法：400 + 300 + (1,100 − 400) = 1,400。收入法：工资 1,000 + 利润 (120 + 80 + 200) = 1,400。')]);
O('P02','accounts','名义、实际 GDP 与平减指数','Due beni A e B. Anno 0: qA=10, pA=5, qB=20, pB=2. Anno 1: qA=12, pA=6, qB=18, pB=3. L’anno base è 0.',[
 N('Calcolate il PIL nominale nell’anno 1.',126,'12 × 6 + 18 × 3 = 126。'),N('Calcolate il PIL reale nell’anno 1.',96,'按基年价格：12 × 5 + 18 × 2 = 96。'),N('Calcolate il deflatore nell’anno 1, base 100.',131.25,'126 / 96 × 100 = 131.25。'),N('Calcolate la crescita reale rispetto all’anno 0, in %. ',6.6666667,'基年 GDP = 90；(96 / 90 − 1) × 100 = 6.67%。','%',0.05)]);
O('P03','accounts','CPI 与购买力','Il paniere fisso contiene 10 unità di A e 5 di B. Nell’anno base i prezzi sono 4 e 8; nell’anno successivo sono 5 e 9. Il reddito nominale cresce del 5%.',[
 N('Calcolate l’IPC nell’anno successivo, base 100.',118.75,'基年篮子 80，次年 95；95 / 80 × 100 = 118.75。'),N('Calcolate il tasso d’inflazione.',18.75,'CPI 由 100 到 118.75，通胀 18.75%。','%'),N('Calcolate la variazione ESATTA del reddito reale.',-11.578947,'实际增长 = (1.05 / 1.1875 − 1) × 100 = −11.58%；不能把差值近似当成精确值。','%',0.05)]);
O('P04','accounts','中间品进出口与增加值','A vende 900 ai consumatori, 300 all’estero e 400 a B; importa input per 200. B vende 700 ai consumatori e 500 all’estero; acquista input da A per 400 e importa input per 100. Nessun’altra produzione o scambio.',[
 N('Calcolate il valore aggiunto di A.',1400,'A 的产出 1,600，减去进口中间投入 200，增加值 1,400。'),N('Calcolate il valore aggiunto di B.',700,'B 的产出 1,200 − 国内中间投入 400 − 进口投入 100 = 700。'),N('Calcolate il PIL.',2100,'增加值总和 2,100；支出法 (900 + 700) + (300 + 500) − (200 + 100) = 2,100。'),T('Perché gli input esportati entrano nel PIL, mentre quelli importati sono sottratti?','出口属于对国外的最终支出，计入本国生产；进口投入由国外生产，需要剔除。国内 A→B 的交易在 B 的增加值中扣除，避免重复计算。')]);
O('P05','accounts','GDP 数据的经济解释','Il PIL nominale è 1.200 milioni, il deflatore è 1,20 (base 1) e la popolazione è 50.000. Nell’anno precedente il PIL reale era 980 milioni e la popolazione 49.000.',[
 N('Calcolate il PIL reale, in milioni.',1000,'1,200 / 1.20 = 1,000 百万。','百万'),N('Calcolate il PIL reale pro capite, in euro.',20000,'1,000,000,000 / 50,000 = 20,000 欧元。','€'),T('Il PIL reale e il PIL reale pro capite raccontano la stessa variazione?','实际 GDP 增长约 2.04%，人口也增长约 2.04%；人均实际 GDP 都是 20,000 欧元，保持不变。人均 GDP 也不能完整衡量福利或收入分配。')]);
O('P06','goods','商品市场与平衡预算','C=100+0,6(Y−T); I=150+0,2Y−1.000i; G=200; T=100. Usate i=0,05 per il 5%. Il tasso rimane fisso.',[
 N('Calcolate Y per i=5%.',1700,'0.2Y = 100 − 60 + 150 + 200 − 50 = 340；Y = 1,700。'),N('Calcolate il moltiplicatore di G, a i fisso.',5,'1 / (1 − 0.6 − 0.2) = 5。'),N('Se G e T aumentano entrambi di 100, quanto varia Y?',200,'ΔY = 5 × (100 − 0.6 × 100) = 200。'),T('Commentate: un bilancio invariato implica Y invariato.','错误。政府支出全额进入需求，税收经边际消费倾向影响消费；预算余额不变，并不意味着需求不变。')], 'goods');
O('P07','goods','储蓄变化与需求','C=200+0,5(Y−200); I=200+0,3Y−1.000i; G=300; i=0,05. Considerate il tasso esogeno.',[
 N('Calcolate il reddito d’equilibrio.',2750,'Z = 550 + 0.8Y，Y = 550 / 0.2 = 2,750。'),N('Calcolate il risparmio privato.',1075,'C = 1,475；S = Y − T − C = 2,750 − 200 − 1,475 = 1,075。'),N('Se c₀ diminuisce di 100, calcolate il nuovo risparmio privato.',925,'Y′ = 2,250，C′ = 100 + 0.5 × 2,050 = 1,125；S′ = 2,250 − 200 − 1,125 = 925。'),T('Spiegate l’effetto sul risparmio aggregato e sugli investimenti.','消费自主项下降使产出下降 500，投资因依赖收入下降 150，私人储蓄也下降 150。政府储蓄 T−G=−100 不变，总储蓄从 975 降至 825，始终等于投资。不能套用“投资固定时储蓄不变”的特例。')], 'goods');
O('P08','finance','货币市场的调整机制','La domanda di moneta è Mᵈ=€Y·L(i); l’offerta di moneta è inizialmente fissa. Il reddito nominale diminuisce.',[
 T('Rappresentate l’effetto su domanda di moneta e tasso d’interesse.','货币需求向左移动，货币供给保持不变，均衡利率下降。'),T('Descrivete il passaggio al nuovo equilibrio tramite il mercato dei titoli.','原利率下出现超额货币供给，人们购买债券；债券价格上升、收益率下降，直到货币需求再次等于供给。'),T('Nel nuovo equilibrio la quantità di moneta detenuta è necessariamente inferiore?','不是。供给固定时，新均衡持有量仍等于原货币供给，变化的是均衡利率。')], 'money');
O('P09','finance','现金比例与货币乘数','Mᵈ=200−1.000i; H=90; c è la quota di moneta detenuta in contante e θ il rapporto riserve/depositi. M=H/[c+θ(1−c)].',[
 N('Con c=0,5 e θ=0,2, calcolate il moltiplicatore.',1.6666667,'1 / [0.5 + 0.2 × 0.5] = 1.6667。','',0.01),N('Calcolate il tasso i di equilibrio, in %. ',5,'M = 150；200 − 1,000i = 150 → i = 0.05 = 5%。','%'),N('Se la BC vende titoli per 12 e H diventa 78, calcolate il nuovo i.',7,'M′ = 130，i′ = (200 − 130) / 1,000 = 7%。','%'),T('Confrontate c=1 con θ=1.','两种情况下乘数都等于 1。c=1 表示全部持有现金；θ=1 表示存款全部作为准备金，不能通过放贷扩张货币。')]);
O('P10','finance','货币与基础货币','Un sistema bancario ha riserve R=60, circolante CI=240 e depositi D=600.',[
 N('Calcolate θ=R/D.',0.1,'60 / 600 = 0.10。','比例',0.001),N('Calcolate M.',840,'M = CI + D = 840。'),N('Calcolate H.',300,'H = CI + R = 300。'),N('Calcolate il moltiplicatore M/H.',2.8,'840 / 300 = 2.8。'),T('Definite c e calcolatelo.','c 是现金占广义货币的比例，240 / 840 = 2/7 ≈ 0.2857。不是现金/存款比率。')]);
O('P11','islm','IS–LM 均衡与政策组合','C=0,6(Y−T); I=300−12i; T=G=200; M/P=750; LM: M/P=Y−10i. In QUESTO esercizio i è in punti percentuali: i=5 significa 5%.',[
 N('Calcolate il tasso d’interesse di equilibrio.',5,'IS：Y = 950 − 30i；LM：Y = 750 + 10i；200 = 40i → i = 5。','%'),N('Calcolate Y.',800,'代入任一方程，Y = 800。'),N('La BC porta i a 8%. Con G fisso, quali tasse mantengono Y=800?',140,'800 = 0.6(800 − T) + 300 − 12 × 8 + 200；T = 140。央行调整货币供给以达到新政策利率。'),T('Qual è il saldo pubblico dopo il cambiamento?','T − G = −60，为 60 的赤字。利率上升抑制投资，减税支持消费以抵消其影响。')], 'islm');
O('P12','islm','保持产出、改善财政余额','C=100+0,6(Y−T); I=100−10i; G=T=100; LM: M/P=Y−10i e M/P=500. i è espresso in punti percentuali.',[
 N('Calcolate Y iniziale.',528.5714286,'IS：Y = 600 − 25i；LM：Y = 500 + 10i；i = 100/35，Y = 528.57。','',0.05),N('Calcolate i iniziale.',2.8571429,'i = 100 / 35 = 2.857%。','%',0.03),N('Se ΔT=50, quale ΔG mantiene invariata la IS?',30,'保持自主需求：ΔG = c₁ΔT = 0.6 × 50 = 30。'),T('Di quanto migliora il saldo pubblico?','Δ(T − G) = 50 − 30 = 20。尽管支出也上升，税收增加更多；IS 与 LM 都不变，产出、利率不变。')], 'islm');
O('P13','islm','风险溢价、挤兑与政策限制','Nel modello IS–LM esteso, I=I(Y,r+x). La BC fissa il tasso r, quindi la LM è orizzontale. Un peggioramento della solvibilità bancaria aumenta x.',[
 T('Come cambiano IS, LM, Y e r?', '投资融资成本 r+x 上升，IS 左移；在央行政策利率不变的假设下 LM 不变，Y 下降，r 不变。'),T('Quale intervento monetario può sostenere Y?', '降低政策利率，使水平 LM 下移，刺激投资；若存在零利率下限或传导受阻，未必能完全恢复原产出。'),T('Commentate: la BC può sempre annullare la recessione.','错误。政策空间、零利率下限与银行传导障碍都可能限制作用；需要写明预期通胀等假设。')], 'horizontal');
O('P14','labor','WS–PS 与竞争程度','WS: W/P=1−3u. PS: W/P=1/(1+μ). La produttività è 1 e μ=0,2. u è una frazione: 0,05 significa 5%.',[
 N('Calcolate il salario reale.',0.8333333,'PS：1 / 1.2 = 0.8333。','',0.005),N('Calcolate uₙ, in %. ',5.5555556,'1 − 3u = 1/1.2；u = 0.05556 = 5.56%。','%',0.03),N('Se μ aumenta a 0,4, calcolate il nuovo uₙ.',9.5238095,'PS 降至 1/1.4；u = (1 − 1/1.4) / 3 = 9.52%。','%',0.03),T('Spiegate l’effetto della minore concorrenza.','加成上升降低企业允许的实际工资，PS 下移；与 WS 相交的自然失业率上升。')], 'labor');
O('P15','labor','生产率与工资','La produttività è A=2 e μ=0,25. WS: W/P=1,8−2u; PS: W/P=A/(1+μ). u è una frazione.',[
 N('Calcolate il salario reale di equilibrio.',1.6,'A / (1+μ) = 2 / 1.25 = 1.6。'),N('Calcolate uₙ, in %. ',10,'1.6 = 1.8 − 2u → u = 0.10 = 10%。','%'),T('Perché A entra nella PS?','单位产品劳动成本为 W/A；价格 P = (1+μ)W/A，因此 W/P = A/(1+μ)。')], 'labor');
O('P16','labor','工资对失业的敏感度','WS: W/P=0,8−0,7u; PS: W/P=0,5. Una riforma modifica la WS in W/P=0,8−0,9u. u è una frazione.',[
 N('Calcolate uₙ iniziale, in %. ',42.8571429,'u = (0.8 − 0.5) / 0.7 = 0.42857，即 42.86%。模型参数为练习设定。','%',0.05),N('Calcolate il nuovo uₙ, in %. ',33.3333333,'u′ = 0.3 / 0.9 = 0.33333，即 33.33%。','%',0.05),T('Rappresentate e spiegate il cambiamento.','WS 绕截距变陡，给定失业率下要求的实际工资更低；PS 不变，交点向更低的失业率移动。')], 'labor');
O('P17','labor','反通胀的失业代价','πₜ−πₜ₋₁=−0,5(uₜ−6). Inflazione e disoccupazione sono entrambe espresse in punti percentuali.',[
 N('Quale u riduce l’inflazione di 3 punti in un anno?',12,'−3 = −0.5(u−6) → u = 12%。','%'),N('Con u=8%, quanti anni servono per una riduzione di 3 punti?',3,'每年下降 1 个百分点，保持 u=8% 三年可累计下降 3 个百分点。','年'),T('Distinguete una riduzione dell’inflazione da una diminuzione dei prezzi.','通胀下降是价格上涨变慢；只有通胀降至负值，整体价格水平才下降。')]);
O('P18','labor','工资指数化与通胀惯性','πₜ=λπₜ+(1−λ)πₜ₋₁−α(uₜ−uₙ). λ=0,5; α=1,5; uₙ=0,06; u=0,04; πₜ₋₁=0,04. I parametri sono frazioni.',[
 N('Calcolate πₜ, in %. ',10,'Δπ = −1.5/(1−0.5) × (0.04−0.06) = 0.06；πₜ = 0.10。','%'),N('Calcolate πₜ₊₁, con u invariato.',16,'每期通胀增加 6 个百分点，次期 16%。','%'),N('Calcolate πₜ₊₂.',22,'再增加 6 个百分点，得到 22%。','%'),T('Come cambia la sensibilità all’output gap con λ maggiore?','有效斜率为 α/(1−λ)；λ 越大，给定失业缺口导致的通胀变化越大，工资价格反馈更强。')]);
O('P19','labor','连接产出、利率与通胀','L=2.000, uₙ=10%, A=1. IS: Y=2.000−2.500r, con r in frazioni; la BC fissa r=0,10. PC: Δπ=0,1(Y−Yₙ)/L. Un aumento di G sposta l’intercetta IS da 2.000 a 2.200.',[
 N('Calcolate Yₙ.',1800,'Yₙ = A L(1−uₙ) = 1 × 2,000 × 0.9 = 1,800。'),N('Calcolate Y iniziale.',1750,'2,000 − 2,500 × 0.10 = 1,750。'),N('Calcolate rₙ iniziale, in %. ',8,'1,800 = 2,000 − 2,500rₙ → rₙ = 0.08。','%'),N('Dopo lo shock fiscale, con r invariato, calcolate Δπ in punti percentuali.',0.75,'Y′ = 1,950；Δπ = 0.1 × 150 / 2,000 = 0.0075，即 +0.75 个百分点。','百分点',0.01),T('Quale r stabilizza ora l’inflazione?','新自然利率为 (2,200 − 1,800)/2,500 = 16%。央行提高利率使产出回到潜在水平。')], 'pc');
O('P20','labor','滞胀与供给冲击','L’economia è inizialmente in equilibrio di medio periodo. Un aumento permanente del markup riduce Yₙ. Usate IS–LM–PC con tasso di policy.',[
 T('Descrivete l’effetto iniziale su inflazione e output gap.','潜在产出下降；若当前产出未变，缺口变为正，通胀开始上升。'),T('Come può reagire la BC interessata a stabilizzare l’inflazione?','紧缩货币政策提高利率、降低实际产出至新的潜在水平，调整期间出现产出下降与通胀上升。'),T('Perché una stimolazione della domanda non elimina da sola il problema?','需求刺激不能直接恢复供给能力，可能加剧通胀；需要区分需求管理与影响潜在产出的政策。')], 'pc');
O('P21','labor','信心下降与财政抵消','Si parte da Y=Yₙ nel modello IS–LM–PC; LM orizzontale. c₁=0,6. La fiducia riduce c₀ di 100; il governo riduce T di 100.',[
 N('Calcolate la variazione della domanda autonoma.',-40,'ΔA = Δc₀ − c₁ΔT = −100 + 60 = −40。'),T('Come cambiano IS, output gap e inflazione nel breve periodo?','IS 左移，产出低于潜在水平，缺口为负，通胀下降；政策利率不变。'),T('Quale politica può riportare Y al livello naturale? È sempre possibile?','降息可使 LM 下移、扩大投资；受零利率下限等限制，未必总能完全抵消冲击。'),T('A Y ripristinato, la composizione della domanda torna identica?','不会。在原产出下消费净下降 40，需要投资净上升 40 补足；政府支出不变。')], 'horizontal');
O('P22','growth','折旧率与稳态','Nel modello di Solow senza crescita demografica o progresso tecnico: y=√k, s=0,2, δ=0,05. In stato stazionario s√k=δk.',[
 N('Calcolate k* iniziale.',16,'√k* = s/δ = 4，所以 k* = 16。'),N('Se δ sale a 0,10, calcolate il nuovo k*.',4,'√k* = 2，k* = 4。'),T('Rappresentate lo shock e spiegate il percorso.','折旧线变陡，原稳态投资不足以弥补折旧，资本逐步下降；新稳态人均产出由 4 降至 2。')], 'solow');
O('P23','growth','储蓄、消费与黄金律','y=√k, δ=0,1; nessuna crescita demografica o tecnica. Il tasso di risparmio passa da s=0,2 a s=0,4.',[
 N('Calcolate y* iniziale.',2,'k* = (0.2/0.1)² = 4，y* = 2。'),N('Calcolate y* finale.',4,'k* = 16，y* = 4。'),N('Calcolate c* finale.',2.4,'c* = (1−0.4) × 4 = 2.4，原值为 1.6。'),T('Cosa accade al consumo subito e al tasso di crescita di lungo periodo?','资本不能瞬间调整，储蓄率上升当期消费下降。过渡期资本增长加快；无技术进步和人口增长时，最终人均增长率仍为零。'),T('Un s maggiore aumenta sempre c*?','不是。过度储蓄可能降低稳态消费；本函数黄金律为 s=0.5，需比较初始、最终状态，不能只看产出。')], 'solow');
O('P24','growth','有效劳动与增长率','Solow con progresso tecnico gA=2%, crescita del lavoro n=1%, δ=5%; approssimazione δ+n+gA. y=f(k) per unità di lavoro effettivo. Il risparmio diminuisce.',[
 N('Calcolate il tasso di crescita di Y/N sul sentiero bilanciato.',2,'平衡增长路径上，人均/每工人产出按技术进步率增长。','%'),N('Calcolate il tasso di crescita aggregato di Y, con l’approssimazione del corso.',3,'总产出增长率约 n + gA = 3%。','%'),T('Come cambiano k*=K/(AN) e la crescita durante la transizione?','储蓄率降低使有效劳动单位资本稳态下降。过渡期每工人产出增长慢于 gA；最终增长率恢复到 2%，水平低于原路径。')], 'solow');
O('P25','growth','收敛与技术进步','Il prodotto per lavoratore cresce del 3% e l’occupazione cresce dell’1%.',[
 N('Se l’economia è sul sentiero bilanciato, calcolate gA.',3,'平衡增长路径上 g(Y/N)=gA，因此 gA=3%。','%'),N('Calcolate la crescita aggregata approssimata di Y.',4,'gY ≈ gN + gA = 1% + 3% = 4%。','%'),T('Se k è inferiore a k*, cosa aggiunge la convergenza alla crescita di Y/N?','低于稳态时资本深化对增长有额外贡献；在其他条件相同时，每工人产出的增长可高于技术进步率。')]);
O('S01','expectations','终身财富与消费平滑','Ricchezza finanziaria=60.000 euro; valore attuale della ricchezza umana=1.140.000 euro. Restano 30 anni. Assumete r=0, nessun lascito e nessun vincolo di credito. Reddito corrente=25.000 euro.',[
 N('Calcolate la ricchezza totale.',1200000,'60,000 + 1,140,000 = 1,200,000 欧元。','€'),N('Calcolate il consumo annuo costante.',40000,'1,200,000 / 30 = 40,000；题设 r=0。','€'),N('Quanto va preso a prestito quest’anno?',15000,'40,000 − 25,000 = 15,000 欧元。','€'),N('Una vincita inattesa di 9.000 aumenta il consumo annuo di quanto?',300,'新增财富在剩余 30 年平滑消费：9,000/30 = 300 欧元/年。','€/年')]);
O('S02','expectations','短期降息与收益率曲线','Nella teoria delle aspettative, ignorate premi a termine e usate iₙ≈media dei tassi brevi attuali e attesi. Il tasso breve corrente scende da 4% a 2%; tutti i tassi brevi FUTURI attesi restano al 4%.',[
 N('Calcolate il rendimento a due periodi dopo lo shock.',3,'(2% + 4%) / 2 = 3%。','%'),N('Calcolate il rendimento a quattro periodi.',3.5,'(2 + 4 + 4 + 4)/4 = 3.5%。','%'),T('Rappresentate la nuova curva e spiegate perché lo spostamento non è parallelo.','期限 n 的收益率下降 2/n 个百分点；越短期限受当前降息影响越大。未来短期利率预期没有改变。')], 'yield');
O('S03','expectations','从收益率反推预期','Usate la teoria delle aspettative senza premio a termine, nella forma approssimata. i₁=3%, i₂=3,5%, i₃=4%.',[
 N('Calcolate il tasso breve atteso nel periodo 2.',4,'i₂ᵉ = 2 × 3.5 − 3 = 4%。','%'),N('Calcolate il tasso breve atteso nel periodo 3.',5,'i₃ᵉ = 3 × 4 − 2 × 3.5 = 5%。','%'),T('Interpretate la struttura a termine.','在无期限溢价的假设下，市场预期短期利率由 3% 升至 4%、5%。不能在未控制期限溢价时把真实曲线完全解释为政策预期。')]);
O('S04','expectations','未来政策如何影响当期','Usate IS–LM con aspettative, LM corrente orizzontale e inflazione attesa nulla. Considerate un annuncio credibile di espansione monetaria FUTURA.',[
 T('Come cambiano tassi futuri attesi e domanda corrente?','未来利率预期下降可能提高未来收入预期，支持当期消费与投资；当期 IS 右移。'),T('Il tasso di policy corrente deve diminuire?','不必。题设当期政策不变，水平 LM 不动，当期利率不变但产出上升。'),T('Che cosa cambia se l’annuncio non è credibile?','若未改变预期，预期渠道可能几乎不起作用；需要区分政策宣布、预期改变与实际执行。')], 'horizontal');
O('S05','expectations','政策与股票价格','Un titolo paga un unico dividendo atteso D=110 tra un periodo. Nessun premio per il rischio. Q=D/(1+r). Il tasso è inizialmente 10%.',[
 N('Calcolate Q iniziale.',100,'110 / 1.10 = 100。'),N('Se r scende al 5% e D resta 110, calcolate Q.',104.7619048,'110 / 1.05 = 104.76。','',0.05),N('Se invece D scende a 99 e r resta 10%, calcolate Q.',90,'99 / 1.10 = 90。'),T('Una recessione e un taglio dei tassi implicano necessariamente Q maggiore?','不一定。预期股息减少降低价格，贴现率下降提高价格，净效应取决于幅度，也可能受风险溢价影响。')]);
O('S06','open','利率平价与汇率方向','E indica unità di valuta estera per UNA unità di valuta domestica. E=1,5; Eᵉ=1,425; i*=4%. Usate i≈i*−(Eᵉ−E)/E.',[
 N('Calcolate il tasso domestico i.',9,'预期本币贬值 5%，i ≈ 4% − (−5%) = 9%。','%'),T('Se i>i*, il titolo domestico è necessariamente più conveniente in valuta comune?','不是。预期本币贬值抵消名义利率优势；满足 UIP 时，共同货币下的预期回报相等。'),T('Precisate la convenzione di E e il significato di Eᵉ<E.','E 为本币可换外币数量，E 下降表示本币贬值。采用倒数报价时升贬值方向也要相应转换。')]);
O('S07','open','从利差推断汇率预期','Il tasso domestico è 3%, quello estero è 5%; E è valuta estera per unità domestica. Usate UIP approssimata.',[
 N('Calcolate la variazione percentuale attesa di E.',2,'(Eᵉ−E)/E ≈ i*−i = 2%，本币预期升值。','%'),N('Se E=1,20, calcolate Eᵉ.',1.224,'1.20 × 1.02 = 1.224。','',0.002),T('Perché un tasso domestico più basso può essere compatibile con UIP?','本币预期升值可补偿更低的国内利率，使预期共同货币回报相同。')]);
O('S08','open','开放经济的连续计算','C=100+0,6(Y−100); I=100−1.000i; G=200; X=100; IM=0,1Y (già in beni domestici). LM: 400=0,5Y−1.000i. i*=4%; E=1; UIP approssimata. i è una frazione.',[
 N('Calcolate Y di equilibrio.',840,'IS：0.5Y=440−1,000i；LM：1,000i=0.5Y−400；联立得到 Y=840。'),N('Calcolate i, in %. ',2,'i=(420−400)/1,000=0.02，即 2%。','%'),N('Calcolate NX.',16,'100 − 0.1 × 840 = 16，为贸易顺差。'),N('Calcolate Eᵉ.',1.02,'0.02 = 0.04 − (Eᵉ−1)；Eᵉ=1.02。','',0.002),T('Spiegate come un apprezzamento tende a influire su NX, a prezzi dati.','E 上升表示本币升值，国内商品相对更贵，通常出口减少、进口增加，NX 下降。该方向依赖通常的贸易反应假设。')], 'islm');
O('S09','fiscal','债务递推与偿债','Bₜ₋₁=0; Gₜ−Tₜ=10 solo nell’anno t. Negli anni t+1 e t+2 il saldo primario è zero. r=10%; il debito va rimborsato a fine t+3. Bₜ=(1+r)Bₜ₋₁+Gₜ−Tₜ.',[
 N('Calcolate Bₜ.',10,'初始债务为零，当期赤字 10，Bₜ=10。'),N('Calcolate Bₜ₊₂.',12.1,'Bₜ₊₁=11；Bₜ₊₂=12.1。'),N('Quale avanzo primario serve in t+3?',13.31,'T−G = 1.1 × 12.1 = 13.31，偿还本金及最后一期利息。'),T('Distinguete stock di debito, deficit totale e saldo primario.','债务是时点存量；总赤字为本期流量，包含利息；初级赤字 G−T 不含利息。题设下债务变化等于总赤字。')]);
O('S10','fiscal','持续减税与债务稳定','Debito iniziale nullo. Il governo riduce T di 2 nel primo anno e di un ulteriore 1 nel secondo; i tagli sono permanenti e G invariato. r=1%.',[
 N('Calcolate B dopo il primo anno.',2,'第一年初级赤字为 2。'),N('Calcolate B dopo il secondo anno.',5.02,'1.01 × 2 + 3 = 5.02。'),N('Calcolate B dopo il terzo anno.',8.0702,'1.01 × 5.02 + 3 = 8.0702。','',0.001),N('Quale avanzo primario azzera B alla fine del quarto anno?',8.150902,'1.01 × 8.0702 = 8.150902。','',0.001),T('Con un debito di 2, un saldo primario nullo basta a stabilizzare B?','不够。利息支出使债务增至 2.02；保持债务存量不变需要初级盈余 rB = 0.02。')]);
O('S11','fiscal','债务率、利率与风险','b₀=B/Y=1; deficit nominale/PIL=4%; i=10%; π=7%; g=2%. Usate r≈i−π e bₜ=(1+r−g)bₜ₋₁+d, con d=(G−T)/Y costante. I dati del primo anno sono approssimati come nel corso.',[
 N('Calcolate d, in %. ',-6,'d = 4% − 10% × 1 = −6%，表示初级盈余。','%'),N('Calcolate il deficit totale corretto per inflazione/PIL.',-3,'r≈3%；r b + d = 3% − 6% = −3%。这是经通胀调整的总余额，不能称为另一个初级余额。','%'),N('Calcolate b₁, in %. ',95,'b₁ = 1.01 × 1 − 0.06 = 0.95，即 95%。下降 5 个百分点。','%'),N('Iterate la stessa relazione per 10 anni: calcolate b₁₀.',47.6889373,'逐期应用 bₜ=1.01bₜ₋₁−0.06，得 b₁₀≈0.476889。不能改成每年乘以 0.95。','%',0.05),T('Una svalutazione attesa aumenta i a 20%, con π invariata e g=−2%: calcolate Δb al valore iniziale b=1.','r≈13%；Δb≈(0.13−(−0.02))×1−0.06=0.09，债务率增加 9 个百分点。题设初级余额仍保持 −6%。')]);
O('S12','fiscal','债务率的固定点与稳定性','r=10%; g=9%; avanzo primario/PIL=10%. Usate bₜ=(1+r−g)bₜ₋₁−0,10 e b₀=1.',[
 N('Calcolate il valore fisso b* che lascia b invariato.',10,'b*=1.01b*−0.10；0.01b*=0.10 → b*=10，即 1000%。','比例'),N('Calcolate b₁.',0.91,'1.01 × 1 − 0.10 = 0.91。','比例',0.001),N('Calcolate b₂.',0.8191,'1.01 × 0.91 − 0.10 = 0.8191。','比例',0.001),T('Il punto fisso è stabile? Disegnate la retta rispetto alla bisettrice.','斜率 1.01 > 1，固定点不稳定。初始 b=1 低于 b*=10，持续初级盈余使债务率逐步下降；数学模型可延伸到负值，表示政府净资产。')], 'debt');
M('Q01','primo','accounts','增加值','Un’impresa vende per 500 e usa input intermedi per 180. Il suo valore aggiunto è:', ['320','500','680','180'],'增加值 = 产出 − 中间投入 = 320。工资属于增加值的分配，不作为中间投入扣除。');
M('Q02','primo','accounts','出口中间品','Un input prodotto internamente ed esportato:', ['Entra nel PIL tramite le esportazioni','È sempre escluso perché intermedio','È sottratto dal PIL come importazione','Entra solo se consumato in patria'],'该产品由本国生产，出口是国外对本国产品的最终支出。');
M('Q03','primo','accounts','实际 GDP','Il PIL nominale cresce del 10% e il deflatore del 10%. La crescita reale esatta è:', ['0%','10%','20%','−10%'],'1.10/1.10 − 1 = 0。');
M('Q04','primo','accounts','CPI 与平减指数','Quale affermazione è corretta?', ['L’IPC usa un paniere di consumo; il deflatore riguarda la produzione interna','L’IPC esclude sempre i beni importati','Il deflatore usa sempre un paniere fisso di consumatori','IPC e deflatore sono identici per definizione'],'CPI 针对消费篮子，可包含进口消费品；GDP 平减指数针对本国生产的最终产出。');
M('Q05','primo','goods','乘数','C=100+0,6Y; I=50+0,2Y; G è esogena. Il moltiplicatore di G a tasso fisso è:', ['5','2,5','1,25','0,2'],'1/(1−0.6−0.2) = 5，投资的收入效应也进入乘数。');
M('Q06','primo','goods','平衡预算','Con c₁=0,6, investimento fisso e i fisso, ΔG=ΔT=100 implica:', ['ΔY=100','ΔY=0','ΔY=250','ΔY=−100'],'ΔY = (100 − 0.6×100)/(1−0.6)=100。这里与投资依赖收入的题目不同。');
M('Q07','primo','finance','债券与利率','Per un titolo a pagamento futuro fisso, se il prezzo corrente aumenta:', ['Il rendimento diminuisce','Il rendimento aumenta','Il rendimento non cambia mai','La quantità di moneta deve annullarsi'],'固定偿付时价格和收益率反向变化。');
M('Q08','primo','finance','货币供给','CI=200, D=500, R=50. La base monetaria è:', ['250','700','550','750'],'H=CI+R=250；广义货币 M=CI+D=700。');
M('Q09','primo','finance','货币乘数','Con c=0,2 e θ=0,1, il moltiplicatore è circa:', ['3,57','10','5','1,28'],'1/[0.2+0.1(0.8)]=1/0.28≈3.57。');
M('Q10','primo','islm','LM 的设定','Se la BC fissa il tasso di policy nel modello del corso, la LM è:', ['Orizzontale al tasso scelto','Sempre verticale','Sempre inclinata negativamente','Assente perché non esiste moneta'],'在目标利率设定下，央行调整货币供给以维持该利率，LM 水平；固定货币供给模型则不同。');
M('Q11','primo','islm','风险溢价','Con I=I(Y,r+x) e r fissato, un aumento di x tende a:', ['Spostare IS a sinistra e ridurre Y','Spostare IS a destra','Ridurre il costo del credito','Spostare automaticamente LM in basso'],'融资利率 r+x 上升抑制投资，IS 左移；当期政策利率不变。');
M('Q12','primo','labor','工资定价','Con A=2 e μ=0,25, la PS implica W/P=', ['1,6','2,5','0,625','0,8'],'W/P=A/(1+μ)=2/1.25=1.6。');
M('Q13','primo','labor','通胀缺口','Con πₜ−πₜ₋₁=−0,5(uₜ−6), se uₜ=8%:', ['L’inflazione scende di 1 punto','L’inflazione scende dell’8%','Il livello dei prezzi scende certamente','L’inflazione sale di 1 punto'],'Δπ=−0.5(8−6)=−1 个百分点。通胀下降不必然意味着价格下降。');
M('Q14','primo','labor','自然利率','Il tasso naturale rₙ nel modello IS–LM–PC è quello che:', ['Porta Y a Yₙ e stabilizza l’inflazione','Rende tutti i tassi nominali nulli','Massimizza sempre Y','Elimina ogni forma di disoccupazione'],'使产出等于潜在产出、缺口为零，从而通胀稳定。');
M('Q15','primo','labor','供给冲击','Un aumento permanente del markup, a parità di WS, tende a:', ['Aumentare uₙ e ridurre Yₙ','Ridurre uₙ e aumentare Yₙ','Lasciare invariata PS','Aumentare il salario reale offerto'],'加成增加使 PS 下移，实际工资下降，自然失业率上升、潜在产出下降。');
M('Q16','primo','growth','Solow 稳态','Senza crescita demografica e tecnica, in stato stazionario:', ['sf(k*)=δk*','s=δ per ogni funzione','Il capitale non si deprezza','La crescita pro capite è sempre positiva'],'投资正好弥补折旧，资本每工人不再变化。');
M('Q17','primo','growth','储蓄率提高','Un aumento di s nel Solow standard implica sul sentiero di lungo periodo:', ['Un livello di y più alto, non necessariamente crescita pro capite permanentemente più alta','Una crescita pro capite permanentemente più alta senza progresso tecnico','Consumo più alto immediatamente','Capitale inferiore'],'储蓄率影响稳态水平；持续每工人增长来自技术进步。当期消费反而下降。');
M('Q18','primo','growth','平衡增长路径','Se n=1% e gA=2%, la crescita di Y/N sul sentiero bilanciato è:', ['2%','3%','1%','0%'],'每工人产出增长率为技术进步率；总产出约增长 3%。');
M('Q19','primo','goods','投资对利率的反应','Se I=100−1.000i e i passa da 0,05 a 0,04, a Y dato:', ['I aumenta di 10','I diminuisce di 10','I aumenta di 1.000','I resta invariato'],'ΔI=−1,000×(−0.01)=+10。利率按小数代入。');
M('Q20','primo','labor','指数化','Con Δπ=−α(u−uₙ)/(1−λ), aumentando λ<1:', ['Aumenta la sensibilità di Δπ al gap di disoccupazione','La sensibilità diminuisce','La curva diventa sempre piatta','Il tasso naturale diventa automaticamente zero'],'1−λ 变小，系数绝对值变大。');
M('Q21','secondo','expectations','消费平滑','Con r=0 e 20 anni residui, una ricchezza inattesa di 10.000 aumenta il consumo annuo costante di:', ['500','10.000','200','0'],'新增财富分摊到 20 年，10,000/20=500。');
M('Q22','secondo','expectations','收益率反推','Senza premi a termine, i₁=2% e i₂=3%. Il tasso breve atteso nel secondo periodo è circa:', ['4%','3%','1%','5%'],'2×3−2=4%。');
M('Q23','secondo','expectations','降息与期限','Se solo il tasso breve corrente scende di 2 punti, il rendimento a 4 periodi scende circa di:', ['0,5 punti','2 punti','8 punti','0 punti'],'均值中只有一期变动，2/4=0.5 个百分点。');
M('Q24','secondo','expectations','股票价格','Con dividendi attesi invariati, una riduzione del tasso di sconto tende a:', ['Aumentare il prezzo delle azioni','Diminuire il prezzo delle azioni','Lasciarlo invariato per definizione','Annullare i dividendi'],'贴现率下降提高未来股息现值；若股息或风险溢价同时变化，需分析净效应。');
M('Q25','secondo','expectations','未来政策','Con LM corrente orizzontale, un annuncio credibile di minori tassi futuri può:', ['Aumentare la domanda corrente senza cambiare il tasso corrente','Cambiare solo l’economia futura in ogni caso','Far diventare verticale la LM','Eliminare la dipendenza del consumo dalle aspettative'],'预期渠道可改变当期消费和投资，移动 IS，即使当期利率不变。');
M('Q26','secondo','open','汇率报价','E è valuta estera per unità domestica. Se E aumenta:', ['La valuta domestica si apprezza','La valuta domestica si deprezza','La valuta estera si apprezza necessariamente','Nessun prezzo relativo può cambiare'],'一单位本币换得更多外币，即本币升值。');
M('Q27','secondo','open','UIP','Con i*=4% e deprezzamento domestico atteso del 3%, UIP approssimata richiede:', ['i≈7%','i≈1%','i≈4%','i≈−3%'],'国内利率需高出约 3 个百分点，补偿预期贬值。');
M('Q28','secondo','open','利差与回报','Quando vale UIP, un titolo con tasso nominale maggiore:', ['Non ha necessariamente un rendimento atteso maggiore in valuta comune','È sempre l’investimento migliore','È privo di rischio','Viola necessariamente l’assenza di arbitraggio'],'需要同时计入汇率预期，不能只比较名义利率。');
M('Q29','secondo','open','净出口','A prezzi dati e con reazioni commerciali usuali, un apprezzamento reale tende a:', ['Ridurre NX','Aumentare NX sempre','Lasciare immutate esportazioni e importazioni','Azzerare il reddito estero'],'本国商品相对更贵，出口受抑制、进口受促进。');
M('Q30','secondo','open','政策与汇率制度','Nel Mundell–Fleming standard con perfetta mobilità dei capitali e cambio fisso, una politica monetaria autonoma:', ['È vincolata dalla difesa della parità','È sempre più efficace che a cambio flessibile','Non incontra vincoli','Rende superflui gli interventi valutari'],'为维持固定汇率，央行需干预，货币自主性受资本流动与汇率目标约束。此题为大纲延伸。');
M('Q31','secondo','fiscal','存量与流量','Quale variabile è uno stock?', ['Il debito pubblico a fine anno','Il disavanzo annuale','La spesa pubblica annuale','Gli interessi pagati nell’anno'],'债务是时点存量；赤字、支出与利息支付是期间流量。');
M('Q32','secondo','fiscal','初级余额','Il disavanzo primario è:', ['G−T, escludendo interessi','G−T+iB, includendo interessi','Lo stock di debito','Sempre uguale al disavanzo totale'],'初级余额排除利息；总赤字才包含利息。');
M('Q33','secondo','fiscal','偿债','B=100, r=5%. Per azzerare il debito alla fine dell’anno, serve un avanzo primario di:', ['105','100','5','95'],'B′=1.05×100−盈余=0，因此盈余为105。');
M('Q34','secondo','fiscal','稳定债务率','Usando Δb≈(r−g)b+d, con r=4%, g=2%, b=1, per Δb=0 serve:', ['Un avanzo primario del 2% del PIL','Un disavanzo primario del 2%','Un saldo primario nullo','Un avanzo del 4%'],'d=−(0.04−0.02)×1=−0.02，为初级盈余 2%。');
M('Q35','secondo','fiscal','百分比与百分点','b passa da 100% a 95%. La variazione è:', ['−5 punti percentuali, e −5% relativamente al valore iniziale','−95 punti percentuali','Sempre −5% in ogni anno futuro','+5 punti percentuali'],'首年从100到95，下降5个百分点且相对降幅5%；不意味着以后都按0.95倍变化。');
M('Q36','secondo','fiscal','实际利率','Secondo Fisher approssimato, i=8%, πᵉ=3% implica r≈', ['5%','11%','3%','8%'],'r≈i−πᵉ=5%。精确式为(1+i)/(1+πᵉ)−1，题目要求近似。');
M('Q37','secondo','fiscal','债务递推','Con bₜ=1,01bₜ₋₁−0,06 e b₀=1, b₂ è:', ['0,8995','0,9025','0,95','1,02'],'b₁=0.95；b₂=1.01×0.95−0.06=0.8995。不能把递推替换成0.95²。');
M('Q38','secondo','policy','李嘉图等价','Nell’equivalenza ricardiana, con le ipotesi necessarie, un taglio di imposte finanziato da debito:', ['Può essere risparmiato in previsione di imposte future','Aumenta necessariamente il consumo dello stesso importo','Elimina il vincolo di bilancio pubblico','Non implica mai imposte future'],'理性预期、无流动性约束等条件下，家庭预计未来税收增加并储蓄减税所得。现实中这些假设未必成立。');
M('Q39','secondo','policy','非常规货币政策','Il quantitative easing consiste tipicamente in:', ['Acquisti di attività per influire su rendimenti e condizioni finanziarie','Un aumento automatico delle imposte','Una riduzione del capitale produttivo','La fissazione diretta di ogni prezzo'],'资产购买可影响长期收益率与金融条件；不是央行直接规定所有利率或物价。');
M('Q40','secondo','fiscal','财政可持续性','Un aumento di r a parità di g, b>0 e saldo primario tende a:', ['Peggiorare la dinamica del rapporto debito/PIL','Migliorarla automaticamente','Non influire mai su b','Azzerare il debito'],'Δb≈(r−g)b+d；r 上升使利息与增长差扩大、债务率变化上升。');
